import type { GoldPriceHistoryRange } from '../gold-price-analytics';

export const PG_BUY_LABEL = 'PG BUY - Public Gold buys from customer';
export const PG_SELL_LABEL = 'PG SELL - Public Gold sells to customer';

export const VALUATION_UNAVAILABLE =
  'Current valuation unavailable - no confirmed PG BUY price.';

export const NO_ACTIVE_HOLDINGS = 'No active Gold holdings.';

export const NO_PRICE_HISTORY = 'No confirmed price history available.';

export const LIMITED_PRICE_HISTORY =
  'Limited price history is currently available.';

export const SNAPSHOT_IMPORTANT_NOTE =
  'Portfolio values are estimated using the latest confirmed Public Gold PG BUY price. Historical averages are based on captured observations and may not represent every official intraday Public Gold price update.';

export const PORTFOLIO_HISTORY_ASSUMPTION =
  'Portfolio history reflects currently active holdings projected against historical prices.';

export const PRICE_ANALYTICS_ASSUMPTION =
  'Price analytics are based on confirmed observations stored in the application. Capture frequency may vary and does not represent every official Public Gold price movement.';

export const FOOTER_PRODUCT = 'Generated by Finance App - Gold Module';
export const FOOTER_DISCLAIMER = 'For personal tracking and analysis.';

export const STRATEGY_PRICE_HISTORY_LIMIT = 200;

export type ReportKv = { label: string; value: string };

export type ReportPurchaseRow = {
  purchaseDate: string;
  weightGrams: string;
  invested: string;
  buyPricePerGram: string;
  currentValue: string;
  plRm: string;
  plPercent: string;
  source: string;
  referenceNumber: string | null;
};

export type ReportPriceRow = {
  when: string;
  pgSell: string;
  pgBuy: string;
  spread: string;
  source: string;
};

export type ReportLineSeries = {
  name: string;
  values: number[];
};

export type ReportLineChart = {
  title: string;
  xLabels: string[];
  series: ReportLineSeries[];
  yKind: 'money' | 'grams';
};

export type ReportPeriodStats = {
  range: GoldPriceHistoryRange;
  sampleCount: number;
  daysWithData: number;
  fromDate: string | null;
  toDate: string | null;
  buyChange: string;
  sellChange: string;
  buyHigh: string;
  buyLow: string;
  buyAverage: string;
  sellHigh: string;
  sellLow: string;
  sellAverage: string;
  hasSufficientHistory: boolean;
};

export type GoldSnapshotReportData = {
  kind: 'SNAPSHOT';
  title: string;
  filename: string;
  generatedAtLabel: string;
  portfolioAsOfLabel: string;
  latestPriceAtLabel: string;
  hasHoldings: boolean;
  hasCurrentPrice: boolean;
  currentPortfolio: ReportKv[];
  currentPrice: ReportKv[];
  priceAnalytics: ReportKv[];
  priceAnalyticsNote: string | null;
  portfolioAnalytics: ReportKv[];
  importantNote: string;
  pgBuyCents: number | null;
  pgSellCents: number | null;
  currentValueCents: number | null;
  totalInvestedCents: number;
  totalGrams: string;
};

export type GoldStrategyReportData = {
  kind: 'STRATEGY';
  title: string;
  filename: string;
  requestedRange: GoldPriceHistoryRange;
  generatedAtLabel: string;
  latestPriceAtLabel: string;
  hasHoldings: boolean;
  hasCurrentPrice: boolean;
  hasPriceHistory: boolean;
  overlapNote: string | null;
  executiveSummary: ReportKv[];
  currentPortfolio: ReportKv[];
  valuationNote: string | null;
  costBasis: ReportKv[];
  breakEvenState: string | null;
  periodStats: ReportPeriodStats[];
  priceTrendChart: ReportLineChart | null;
  priceTrendTable: ReportKv[] | null;
  portfolioValueChart: ReportLineChart | null;
  holdingsChart: ReportLineChart | null;
  holdingsSummary: ReportKv[] | null;
  purchases: ReportPurchaseRow[];
  highestReturn: ReportKv[] | null;
  lowestReturn: ReportKv[] | null;
  priceHistory: ReportPriceRow[];
  priceHistoryTruncationNote: string | null;
  dataQuality: ReportKv[];
  assumptions: string[];
  pgBuyCents: number | null;
  pgSellCents: number | null;
  currentValueCents: number | null;
  totalInvestedCents: number;
  totalGrams: string;
};

export const SNAPSHOT_SECTION_TITLES = [
  'Gold Investment Snapshot',
  'Current Portfolio',
  'Current Public Gold Price',
  'Price Analytics Summary',
  'Portfolio Analytics Summary',
  'Important Note',
] as const;

export const STRATEGY_SECTION_TITLES = [
  '1. Executive Summary',
  '2. Current Portfolio',
  '3. Cost Basis & Break-even',
  '4. Public Gold Price Analytics',
  '5. Portfolio Value History',
  '6. Holdings Growth',
  '7. Purchase Performance',
  '8. Price History',
  '9. Data Quality & Assumptions',
] as const;

export const PHASE_5_6_FORBIDDEN = [
  'grams-to-sell',
  'protected capital',
  'profit-taking',
  'target reached',
  'buy planner',
  'scenario analysis',
  'goal-based',
  'monthly budget',
  'financial advice',
  'TAKE PROFIT',
] as const;
